<?php

declare(strict_types=1);

namespace App\Modules\Publishing\Services;

use App\Modules\ContentGeneration\Models\AIRequestLog;
use App\Modules\ContentGeneration\Models\ContentRevision;
use App\Modules\ContentGeneration\Models\GeneratedContent;
use App\Modules\ContentPipeline\Contracts\PublishingQueueInterface;
use App\Modules\ContentPipeline\DTOs\PipelineContext;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class PublishingQueueService implements PublishingQueueInterface
{
    /**
     * Process the publishing queue stage of the content pipeline.
     */
    public function handle(PipelineContext $context): PipelineContext
    {
        if ($context->hasErrors()) {
            return $context;
        }

        try {
            Log::info('PublishingQueueService: Saving generated content and resolving reservation.');

            $run = $context->run;
            $pipeline = $context->pipeline;
            $site = $pipeline->site;
            $topic = $pipeline->topic;
            $promptTemplate = $pipeline->prompt;
            $provider = $pipeline->provider;

            if (!$site || !$topic || !$promptTemplate || !$provider) {
                throw new \RuntimeException('Incomplete pipeline dependencies in context.');
            }

            $title = $context->title ?? ("Article: {$topic->name} - " . now()->format('Y-m-d'));
            $content = $context->generatedContent;
            $promptTokens = $context->metadata['prompt_tokens'] ?? 0;
            $completionTokens = $context->metadata['completion_tokens'] ?? 0;
            $totalTokens = $context->metadata['total_tokens'] ?? 0;
            $estimatedCost = $context->metadata['estimated_cost'] ?? 0.0;
            $rawResponse = $context->metadata['raw_response'] ?? [];
            $executionTimeMs = $context->metadata['execution_time_ms'] ?? 0;
            $reservation = $context->metadata['reservation'] ?? null;

            // Merge featured image info into metadata if present
            $metadataField = [
                'prompt_id' => $promptTemplate->id,
                'prompt_tokens' => $promptTokens,
                'completion_tokens' => $completionTokens,
                'total_tokens' => $totalTokens,
                'cost' => $estimatedCost,
            ];
            if (isset($context->metadata['featured_image_id'])) {
                $metadataField['featured_image_id'] = $context->metadata['featured_image_id'];
            }
            if (isset($context->metadata['featured_image_url'])) {
                $metadataField['featured_image_url'] = $context->metadata['featured_image_url'];
            }
            if (isset($context->metadata['processed_at'])) {
                $metadataField['processed_at'] = $context->metadata['processed_at'];
            }

            $generatedContent = DB::transaction(function () use (
                $pipeline,
                $site,
                $topic,
                $title,
                $content,
                $metadataField,
                $reservation,
                $provider,
                $promptTemplate,
                $executionTimeMs,
                $promptTokens,
                $completionTokens,
                $totalTokens,
                $estimatedCost,
                $rawResponse,
                $run,
                $context
            ) {
                // 1. Create Generated Content record with status = 'draft' (enforced)
                $generatedContent = GeneratedContent::create([
                    'pipeline_id' => $pipeline->id,
                    'site_id' => $site->id,
                    'topic_id' => $topic->id,
                    'title' => $title,
                    'content' => $content,
                    'status' => 'generated', // Enforced generated status
                    'metadata' => $metadataField,
                ]);

                // 2. Create the initial ContentRevision record
                ContentRevision::create([
                    'generated_content_id' => $generatedContent->id,
                    'title' => $title,
                    'content' => $content,
                    'user_id' => null, // generated by system
                ]);

                // 3. Save/log the AIRequestLog (resolving active reservation)
                $requestLogData = [
                    'customer_id' => $site->customer_id,
                    'subscription_id' => $reservation?->subscription_id,
                    'site_id' => $site->id,
                    'provider' => $provider->provider_key,
                    'model' => $provider->default_model ?? 'unknown',
                    'prompt_id' => $promptTemplate->id,
                    'topic_id' => $topic->id,
                    'execution_time_ms' => $executionTimeMs,
                    'prompt_tokens' => $promptTokens,
                    'completion_tokens' => $completionTokens,
                    'total_tokens' => $totalTokens,
                    'estimated_cost' => $estimatedCost,
                    'status' => 'success',
                    'response_metadata' => $rawResponse,
                    'error_log' => null,
                ];

                if ($reservation) {
                    $reservation->update($requestLogData);
                } else {
                    AIRequestLog::create($requestLogData);
                }

                // 4. Update the PipelineRun and ContentPipeline status to 'completed'
                $run->update([
                    'status' => 'completed',
                    'completed_at' => now(),
                ]);
                $pipeline->update(['status' => 'completed']);

                // Associate any generated media items with the generated content ID
                if (!empty($context->mediaItems)) {
                    foreach ($context->mediaItems as $item) {
                        if (isset($item['id'])) {
                            \App\Modules\MediaManager\Models\MediaItem::where('id', $item['id'])
                                ->update(['generated_content_id' => $generatedContent->id]);
                        }
                    }
                }

                return $generatedContent;
            });

            // Store the created GeneratedContent model in the context metadata
            $context->metadata['generated_content_model'] = $generatedContent;

            Log::info('PublishingQueueService: Completed successfully.', [
                'generated_content_id' => $generatedContent->id,
            ]);

        } catch (\Exception $e) {
            Log::error('PublishingQueueService failed: ' . $e->getMessage(), [
                'exception' => $e
            ]);
            $context->addError('publishing_queue', $e->getMessage());
            throw $e;
        }

        return $context;
    }
}
